### ISSUE TITLE
[Feature Request] Call for the permanent PDF link

### ISSUE THREAD

**Issue by zhuhz22** [leverimmy/Principles-of-Signal-Processing-Notes#2]
is it possible to display it publically?

**Comment by leverimmy** [comment]
What exactly do you mean by "display it publicly"? You can always **right-click the hyperlink** and select "Copy Link" instead of left-clicking to access the link directly.

For your convenience, here's the link: https://github.com/leverimmy/Principles-of-Signal-Processing-Notes/releases/download/latest/main.pdf
